insert into carservice_COLOR values ('Red', "ff0000")
insert into carservice_COLOR values ('Green', "00ff00")
insert into carservice_COLOR values ('Blue', "0000ff")
insert into carservice_COLOR values ('White', "ffffff")
insert into carservice_COLOR values ('Black', "000000")
