alter table CARSERVICE_CAR_DEALER add constraint FK_CARSERVICE_CAR_DEALER_ON_COUNTRY foreign key (COUNTRY_ID) references CARSERVICE_COUNTRY(ID);
create unique index IDX_CARSERVICE_CAR_DEALER_UNIQ_NAME on CARSERVICE_CAR_DEALER (NAME) ;
create unique index IDX_CARSERVICE_CAR_DEALER_UNIQ_CODE on CARSERVICE_CAR_DEALER (CODE) ;
create index IDX_CARSERVICE_CAR_DEALER_ON_COUNTRY on CARSERVICE_CAR_DEALER (COUNTRY_ID);
