alter table CARSERVICE_CAR add constraint FK_CARSERVICE_CAR_ON_CAR_DEALER foreign key (CAR_DEALER_ID) references CARSERVICE_CAR_DEALER(ID);
alter table CARSERVICE_CAR add constraint FK_CARSERVICE_CAR_ON_CAR_MAKE foreign key (CAR_MAKE_ID) references CARSERVICE_CAR_MAKE(ID);
alter table CARSERVICE_CAR add constraint FK_CARSERVICE_CAR_ON_EQUIPMENT foreign key (EQUIPMENT_ID) references CARSERVICE_CAR_EQUIPMENT(ID);
create index IDX_CARSERVICE_CAR_ON_CAR_DEALER on CARSERVICE_CAR (CAR_DEALER_ID);
create index IDX_CARSERVICE_CAR_ON_CAR_MAKE on CARSERVICE_CAR (CAR_MAKE_ID);
create index IDX_CARSERVICE_CAR_ON_EQUIPMENT on CARSERVICE_CAR (EQUIPMENT_ID);
