alter table CARSERVICE_PURCHASE_REQUEST add constraint FK_CARSERVICE_PURCHASE_REQUEST_ON_CAR foreign key (CAR_ID) references CARSERVICE_CAR(ID);
alter table CARSERVICE_PURCHASE_REQUEST add constraint FK_CARSERVICE_PURCHASE_REQUEST_ON_BUYER foreign key (BUYER_ID) references CARSERVICE_PERSON(ID);
alter table CARSERVICE_PURCHASE_REQUEST add constraint FK_CARSERVICE_PURCHASE_REQUEST_ON_MANAGER foreign key (MANAGER_ID) references SEC_USER(ID);
create index IDX_CARSERVICE_PURCHASE_REQUEST_ON_CAR on CARSERVICE_PURCHASE_REQUEST (CAR_ID);
create index IDX_CARSERVICE_PURCHASE_REQUEST_ON_BUYER on CARSERVICE_PURCHASE_REQUEST (BUYER_ID);
create index IDX_CARSERVICE_PURCHASE_REQUEST_ON_MANAGER on CARSERVICE_PURCHASE_REQUEST (MANAGER_ID);
